name: Docker Image CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

      
      
jobs:
  tag-image:
    runs-on: ubuntu-latest
    steps:
    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v1
      - uses: docker/setup-buildx-action@v1
      - name: Build image for commit
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.commit.outputs.short }}
